spring:
  application:
    name: carrydrop-api
  
  # 데이터베이스 설정 (기본: NeonDB PostgreSQL)
  datasource:
    url: postgresql://neondb_owner:npg_sdMQ1b5JzAhK@ep-calm-rain-a139nit8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_sdMQ1b5JzAhK
    driver-class-name: org.postgresql.Driver
  
  # SQL 스크립트 자동 실행
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: UTF-8
  
  # HTTP 인코딩 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  # 보안 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# JWT 설정
app:
  jwt:
    secret: ${JWT_SECRET:MySecretKeyForJWT1234567890}
    expiration: 86400000  # 24시간 (밀리초)

# 서버 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    com.carrydrop: DEBUG
    org.springframework.security: DEBUG

# 개발환경별 프로필 설정
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
logging:
  level:
    com.carrydrop: INFO
    root: WARN 